### ISSUE TITLE
Is it possible to create user to user and private group chats using liveoak?

### ISSUE THREAD

**Issue by just10minutes** [liveoak-io/openshift-liveoak-cartridge#3]
Please sugest is  it possible to create user to user and private group chats using liveoak?

Currently it can be used as just an Open chat forum, want to know is it possible to store own contacts and message them just like whatsapp?

If possible can you suggest whats the way forward?

Also facing problem in setting up push, I created a separate push app https://push-tottest.rhcloud.com/ag-push/ using aerogear push on openshift, on my base app(https://liveoak-tottest.rhcloud.com/admin#/applications/chat-html-secured/push) while setting up push URL it says URL End Point Not Responding. Is there anything I am misiing here?

**Comment by kenfinnigan** [comment]
Firstly, sorry for the delayed response, we've all been on leave for the last week or so.

User to user and private group chats are not something we've looked at implementing within the chat example, but I can't think of a reason it wouldn't be possible. For user to user, it probably means adding a "To" field into the chat collection, so that the data being returned from the collection can be filtered such that the user mentioned in "To" is the only one to receive those messages.

Private group chats would likely require a separate collection for each one, but it could probably be achieved in other ways.

We also have a user forum at https://community.jboss.org/en/liveoak which might be a better place to pose these kind of questions.

About push, I haven't tested that personally for a while. It could be related to a Keycloak clash, in that AeroGear UPS embeds its own Keycloak instance for security. I know there is currently work underway to enable it to use an external Keycloak instance, which would make integration with LiveOak easier.

Hope that helps!
